### ISSUE TITLE
 A shameful question. 

### ISSUE THREAD

**Issue by Stevewsw** [baroquerock/sleep-stages-scoring#1]
Hi I‘m Bruce,

I am bounding up in the eeg research.
I wanna redo your brilliant repository, it's a great conversion (py3.x)；
But I found a issue：the `inpy` file in the first cell, In (77)

`
from npzloader import DataLoader
`

I cannot find a module called 'npzloader',  even google.
what does it mean?  Is that you defined ?  
If I can obtain this module if that's true.

It's shame question. no  bother.

It is grateful, if it would be responded. thanks.

**Comment by baroquerock** [comment]
Hi Bruce, 
Thank you for your interest! I am very glad that you found the repo useful. 
Take a look at the root directory. There is a file called npzloader.py:
https://github.com/baroquerock/sleep-stages-scoring/blob/master/npzloader.py

**Comment by Stevewsw** [comment]
yep, thanks, I found it;  hhha
It's my fault, i did not check your repo carefully.

_**Expecting your future work**_, by the way.

[The Sleep-EDF Database](https://www.physionet.org/physiobank/database/sleep-edfx/) updated on 2018-4.  they expanded the Dataset. 



**old:** https://physionet.org/pn4/sleep-edfx/
**new:** https://www.physionet.org/physiobank/database/sleep-edfx/

**Comment by baroquerock** [comment]
Thanks! Will check it out!
